site_name: DataGEMS Front-end Docs

site_url: https://datagems-eosc.github.io/dg-app-ui
repo_url: https://github.com/datagems-eosc/dg-app-ui

nav:
  - Overview: index.md
  - System:
      - Architecture: architecture.md
  - Material:
      - Onboarding: onboarding.md
      - Key Features:
          - Smart Search: smart-search.md
      - Design System:
          - UI Components: ui-components.md
      - Quality Assurance:
          - Testing Methods: qa.md
          - Login in Tests: CypressLogin.md
  - Setup & Monitoring:
      - Security: security.md
      - Automations: automations.md
      - Deployment: deployment.md
      - Code Quality: code-quality.md
    #- Configuration: configuration.md
    #- Logging & Accounting: logging.md
  - License: 
      - License: license.md
      - Licence Report: licence-report.md
  - FAQ & Known Issues: faq.md
  - Home: https://datagems-eosc.github.io/

theme:
  name: "material"
  favicon: images/favicon.jpg
  logo: images/datagems-portal-icon.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    # - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.path
    - navigation.top

extra_css:
  - stylesheets/custom-footer.css

plugins:
  - search
  - mike
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  #  generator: false
  version:
    provider: mike
    alias: true
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/datagems-eosc/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/datagems_eosc
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/datagems_eosc
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@DataGEMS-65n
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/eosc-datagems
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/datagems.eosc/
